#!/usr/bin/bash

which aws_completer &>/dev/null && complete -C '$(which aws_completer)' aws
k version &>/dev/null && source <(kubectl completion bash) && complete -F __start_kubectl k
eksctl version &>/dev/null &&. <(eksctl completion bash)
